name: CD

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build binaries
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        make build

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/bin/mongotron
          build/bin/mongotron-cli
          build/bin/mongotron-migrate
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [release]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3

    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig
        export KUBECONFIG=kubeconfig

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployments/kubernetes/namespace.yml
        kubectl apply -f deployments/kubernetes/configmap.yml
        kubectl apply -f deployments/kubernetes/deployment.yml
        kubectl apply -f deployments/kubernetes/service.yml
        kubectl apply -f deployments/kubernetes/ingress.yml
        kubectl apply -f deployments/kubernetes/hpa.yml
        kubectl rollout status deployment/mongotron -n mongotron

    - name: Verify deployment
      run: |
        kubectl get pods -n mongotron
        kubectl get svc -n mongotron
